name: Terraform Deploy #워크플로우 이름
# main 브랜치에 push가 발생하면 아래 워크플로우가 자동으로 실행
# 코드를 main에 푸시하면 Terraform이 실행
# .github/workflows/terraform.yml

# .github/workflows/terraform.yml
on:
  push:
    paths:
      - '**.tf'
      - '**/terraform.*'
  pull_request:

jobs:
  terraform:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5 

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

